# Generated by Django 3.1.7 on 2021-04-19 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_Advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TB_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_grade', models.IntegerField()),
                ('class_index', models.IntegerField()),
                ('student_nums', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TB_School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of School')),
                ('address', models.CharField(max_length=255, verbose_name='Name of School')),
            ],
        ),
        migrations.CreateModel(
            name='TB_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Student Name')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=20, verbose_name='Student Gender')),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=255, verbose_name='Home Address')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('class_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fstudent_classno', to='app_core.tb_class')),
                ('parent_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fstudent_userno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TB_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, verbose_name='Name of Course')),
                ('school_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fcourse_schoolno', to='app_core.tb_school')),
            ],
        ),
        migrations.AddField(
            model_name='tb_class',
            name='school_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fclass_schoolno', to='app_core.tb_school'),
        ),
        migrations.AddField(
            model_name='tb_class',
            name='teacher_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fclass_userno', to=settings.AUTH_USER_MODEL),
        ),
    ]
