# Generated by Django 3.1.7 on 2021-05-05 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_Param_Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_desc', models.CharField(max_length=255, null=True, verbose_name='Grade Name')),
            ],
        ),
        migrations.CreateModel(
            name='TB_Param_SourceOfStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name_en', models.CharField(max_length=255, null=True, verbose_name='Student Name EN')),
                ('source_name_zh', models.CharField(max_length=255, null=True, verbose_name='Student Name ZH')),
                ('source_name_ko', models.CharField(max_length=255, null=True, verbose_name='Student Name KO')),
            ],
        ),
        migrations.AddField(
            model_name='tb_student',
            name='schoolname',
            field=models.CharField(max_length=255, null=True, verbose_name='School Name'),
        ),
        migrations.CreateModel(
            name='TB_Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=255)),
                ('vehicle_number', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
                ('school_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fvehicle_schoolno', to='app_core.tb_school')),
            ],
        ),
        migrations.CreateModel(
            name='TB_School_Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_type', models.CharField(max_length=255)),
                ('goods_name', models.CharField(max_length=255)),
                ('school_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fgoods_schoolno', to='app_core.tb_school')),
            ],
        ),
        migrations.AddField(
            model_name='tb_student',
            name='grade_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fstudent_gradeno', to='app_core.tb_param_grade'),
        ),
        migrations.AddField(
            model_name='tb_student',
            name='sourceofstudent_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fstudent_sourceofstudentno', to='app_core.tb_param_sourceofstudent'),
        ),
    ]
