# Generated by Django 3.1.7 on 2021-05-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_auto_20210505_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_course',
            name='course_type',
            field=models.CharField(default=(None, '', [], (), {}), max_length=50, null=True, verbose_name='Course Type'),
        ),
        migrations.AddField(
            model_name='tb_course',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tb_course',
            name='price_currency',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tb_course',
            name='price_unit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tb_student',
            name='alt_parent_phone_no',
            field=models.CharField(max_length=20, null=True, verbose_name='Parent Phone No'),
        ),
        migrations.AddField(
            model_name='tb_student',
            name='alt_parent_type',
            field=models.CharField(max_length=20, null=True, verbose_name='Parent Type'),
        ),
        migrations.AddField(
            model_name='tb_student',
            name='parent_phone_no',
            field=models.CharField(max_length=20, null=True, verbose_name='Parent Phone No'),
        ),
        migrations.AddField(
            model_name='tb_student',
            name='parent_type',
            field=models.CharField(max_length=20, null=True, verbose_name='Parent Type'),
        ),
        migrations.AddField(
            model_name='tb_student',
            name='remarks',
            field=models.CharField(max_length=255, null=True, verbose_name='Remarks'),
        ),
    ]
