# Generated by Django 3.1.7 on 2021-05-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_auto_20210505_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_Param_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, verbose_name='Name of Course')),
                ('course_type', models.CharField(max_length=50, null=True, verbose_name='Course Type')),
                ('price', models.FloatField(null=True)),
                ('price_unit', models.CharField(max_length=50, null=True)),
                ('price_currency', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tb_course',
            name='school_no',
        ),
        migrations.AlterField(
            model_name='tb_student',
            name='alt_parent_phone_no',
            field=models.CharField(max_length=20, null=True, verbose_name='Alt Parent Phone No'),
        ),
        migrations.AlterField(
            model_name='tb_student',
            name='alt_parent_type',
            field=models.CharField(max_length=20, null=True, verbose_name='Alt Parent Type'),
        ),
    ]
