# Generated by Django 3.1.7 on 2021-05-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0004_auto_20210505_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_Param_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_quantity', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('price_currency', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
