# Generated by Django 3.1.7 on 2021-05-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0005_tb_param_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_param_items',
            name='price_unit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
