# Generated by Django 3.1.7 on 2021-05-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0006_tb_param_items_price_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_Param_Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(max_length=255)),
                ('price', models.FloatField(null=True)),
                ('price_currency', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
