# Generated by Django 3.1.7 on 2021-05-09 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0009_tb_price_standards_price_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_price_standards',
            name='param_course_no',
        ),
        migrations.AddField(
            model_name='tb_price_standards',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_param_course_id', to='app_core.tb_param_course'),
        ),
    ]
