# Generated by Django 3.1.7 on 2021-05-10 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_core', '0010_auto_20210510_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_student',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Home Address'),
        ),
        migrations.AlterField(
            model_name='tb_student',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tb_student',
            name='class_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fstudent_classno', to='app_core.tb_class'),
        ),
        migrations.AlterField(
            model_name='tb_student',
            name='parent_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fstudent_userno', to=settings.AUTH_USER_MODEL),
        ),
    ]
