# Generated by Django 3.1.7 on 2021-05-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0011_auto_20210511_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_student',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Student Name'),
        ),
    ]
