# Generated by Django 3.1.7 on 2021-05-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0012_auto_20210511_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_student',
            name='gender',
            field=models.CharField(blank=True, max_length=20, verbose_name='Student Gender'),
        ),
    ]
