# Generated by Django 3.1.7 on 2021-05-10 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_core', '0013_auto_20210511_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_student',
            name='class_no',
            field=models.ForeignKey(db_column='class_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fstudent_classno', to='app_core.tb_class'),
        ),
        migrations.AlterField(
            model_name='tb_student',
            name='grade_no',
            field=models.ForeignKey(db_column='grade_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fstudent_gradeno', to='app_core.tb_param_grade'),
        ),
        migrations.AlterField(
            model_name='tb_student',
            name='parent_no',
            field=models.ForeignKey(db_column='parent_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fstudent_userno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tb_student',
            name='sourceofstudent_no',
            field=models.ForeignKey(db_column='sourceofstudent_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fstudent_sourceofstudentno', to='app_core.tb_param_sourceofstudent'),
        ),
    ]
