# Generated by Django 3.1.7 on 2021-05-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0015_tb_param_parenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('unit_price', models.FloatField()),
                ('currency', models.CharField(default='Yuan', max_length=10)),
                ('stock_amount', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TB_Items_Changelogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_username', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField()),
                ('adjust_quantity', models.IntegerField()),
                ('adjust_type', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
