# Generated by Django 3.1.7 on 2021-05-11 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0016_tb_items_tb_items_changelogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_items_changelogs',
            old_name='adjust_quantity',
            new_name='adjust_detail',
        ),
        migrations.RenameField(
            model_name='tb_items_changelogs',
            old_name='modify_username',
            new_name='adjust_username',
        ),
        migrations.RemoveField(
            model_name='tb_items_changelogs',
            name='adjust_type',
        ),
        migrations.AddField(
            model_name='tb_items_changelogs',
            name='item_no',
            field=models.ForeignKey(db_column='item_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='f_itemno', to='app_core.tb_items'),
        ),
        migrations.AlterField(
            model_name='tb_items',
            name='currency',
            field=models.CharField(default='CNY', max_length=10),
        ),
    ]
