# Generated by Django 3.1.7 on 2021-05-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0018_auto_20210512_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_items_changelogs',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
