# Generated by Django 3.1.7 on 2021-05-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0020_auto_20210512_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(max_length=255)),
                ('unit_price', models.FloatField()),
                ('currency', models.CharField(default='CNY', max_length=10)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
