# Generated by Django 3.1.7 on 2021-05-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0022_auto_20210513_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_course',
            old_name='price',
            new_name='price_hour',
        ),
        migrations.AddField(
            model_name='tb_course',
            name='course_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tb_course',
            name='number_of_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tb_course',
            name='price_hour_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tb_course',
            name='price_month',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tb_course',
            name='price_month_status',
            field=models.BooleanField(default=False),
        ),
    ]
