# Generated by Django 3.1.7 on 2021-05-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0023_auto_20210513_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_course',
            name='pricing_standard_nos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tb_course',
            name='remarks',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
