# Generated by Django 3.1.7 on 2021-05-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0025_tb_course_course_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_course',
            name='course_type',
            field=models.CharField(default=0, max_length=50, null=True, verbose_name='Course Type'),
        ),
    ]
